name: Send a message to the channel cyf-nightly

on:
  workflow_run:
    workflows: ["Build CYF"]
    types:
      - completed

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.NIGHTLY_WEBHOOK_URL }}
        content: "The last CYF nightly is ready to be used! Enjoy!"
        username: "GitHub"
        avatar_url: "https://avatars.githubusercontent.com/u/21269430?v=4"
